"""Challenger 1 Empirical Verification Suite for Milestone M2 Remediation.

Empirical challenge of:
1. Cryptographic Signature Verification & Forgery Resistance:
   - Completely fabricated signature string rejected.
   - Signature from a different private key rejected.
   - Tampered clientDataJSON challenge while keeping old signature rejected.
   - Missing signature field rejected.
   - Tampered authenticatorData flags / signCount rejected.
2. Standards-Compliant CBOR Attestation Parsing:
   - Realistic browser CBOR maps (fmt: none, packed).
   - Extraction of standard 65-byte uncompressed EC public key (0x04 || x || y).
   - RP ID hash check and User Presence enforcement.
   - Malformed/truncated CBOR payload resilience.
3. ECDSA NIST P-256 Mathematical Edge Cases:
   - Zero r/s coordinates, out-of-order r/s >= N, points off-curve, point at infinity.
   - Corrupted ASN.1 DER encodings.
4. Anti-Rollback Signature Counter Hardening:
   - Strict HTTP 403 Forbidden on counter regressions and duplicate sign counts.
   - Monotonic increment updates DB state.
   - Synced passkey sign_count=0 exception handling.
"""

import hashlib
import json
import secrets
import struct

import pytest
from django.contrib.auth import get_user_model
from django.test import Client
from django.urls import reverse

from recipes.models import Household, PasskeyCredential, UserProfile
from recipes.webauthn_service import (
    P256_G,
    P256_N,
    _scalar_mul,
    b64url_decode,
    b64url_encode,
    build_mock_assertion_payload,
    cbor_encode,
    der_encode_signature,
    verify_authentication_response,
    verify_ecdsa_p256_signature,
    verify_registration_response,
)

User = get_user_model()


@pytest.fixture
def crypto_user_setup(db):
    """Fixture providing a user, household, and genuine P-256 key pair."""
    hh = Household.objects.create(name="Crypto Adversarial HH")
    user = User.objects.create_user(username="crypto_adversary")
    UserProfile.objects.create(user=user, household=hh)

    # Generate genuine random P-256 keypair
    priv_key = secrets.randbelow(1000000000) + 500000
    pub_point = _scalar_mul(priv_key, P256_G)
    assert pub_point is not None
    pub_bytes = b"\x04" + pub_point[0].to_bytes(32, "big") + pub_point[1].to_bytes(32, "big")
    pub_b64 = b64url_encode(pub_bytes)

    cred = PasskeyCredential.objects.create(
        user=user,
        credential_id="adversarial-test-cred-001",
        public_key=pub_b64,
        sign_count=10,
        name="Crypto Challenger Key",
    )
    return {
        "user": user,
        "household": hh,
        "credential": cred,
        "private_key": priv_key,
        "public_point": pub_point,
        "public_bytes": pub_bytes,
        "public_b64": pub_b64,
    }


# ==============================================================================
# 1. Forgery Resistance Stress Tests
# ==============================================================================

@pytest.mark.django_db
class TestForgeryResistance:
    """Challenge signature verification against fabricated, foreign, tampered, and missing signatures."""

    def test_forged_signature_fabricated_string_rejected(self, crypto_user_setup):
        """Completely fabricated signature string is strictly rejected with HTTP 400."""
        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        payload = build_mock_assertion_payload(
            credential_id=crypto_user_setup["credential"].credential_id,
            challenge=server_chal,
            sign_count=11,
            private_key=crypto_user_setup["private_key"],
        )
        # Fabricate signature
        payload["response"]["signature"] = b64url_encode(b"completely_fabricated_signature_bytes_1234567890")

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 400
        assert "signature" in resp.json().get("error", "").lower()

    def test_forged_signature_different_private_key_rejected(self, crypto_user_setup):
        """Valid signature generated by a different private key is strictly rejected."""
        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        foreign_priv_key = secrets.randbelow(1000000000) + 999999
        payload = build_mock_assertion_payload(
            credential_id=crypto_user_setup["credential"].credential_id,
            challenge=server_chal,
            sign_count=11,
            private_key=foreign_priv_key,  # Sign with attacker's private key
        )

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 400
        assert "signature" in resp.json().get("error", "").lower()

    def test_tampered_challenge_with_old_signature_rejected(self, crypto_user_setup):
        """Tampering challenge in clientDataJSON while retaining genuine signature fails verification."""
        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        # Valid payload for original challenge
        payload = build_mock_assertion_payload(
            credential_id=crypto_user_setup["credential"].credential_id,
            challenge=server_chal,
            sign_count=11,
            private_key=crypto_user_setup["private_key"],
        )

        # Tamper challenge in clientDataJSON
        cd = json.loads(b64url_decode(payload["response"]["clientDataJSON"]).decode("utf-8"))
        cd["challenge"] = b64url_encode(secrets.token_bytes(32))
        payload["response"]["clientDataJSON"] = b64url_encode(json.dumps(cd).encode("utf-8"))

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 400
        assert "challenge" in resp.json().get("error", "").lower()

    def test_missing_signature_field_rejected(self, crypto_user_setup):
        """Assertion missing a signature field is rejected with HTTP 400 Bad Request."""
        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        payload = build_mock_assertion_payload(
            credential_id=crypto_user_setup["credential"].credential_id,
            challenge=server_chal,
            sign_count=11,
            private_key=crypto_user_setup["private_key"],
        )
        del payload["response"]["signature"]

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 400
        assert "missing signature" in resp.json().get("error", "").lower()

    def test_tampered_authenticator_data_rejected(self, crypto_user_setup):
        """Modifying any bit of authenticatorData (e.g. sign count or flags) breaks cryptographic verification."""
        chal = b64url_encode(secrets.token_bytes(32))
        payload = build_mock_assertion_payload(
            credential_id=crypto_user_setup["credential"].credential_id,
            challenge=chal,
            sign_count=11,
            private_key=crypto_user_setup["private_key"],
        )

        raw_ad = bytearray(b64url_decode(payload["response"]["authenticatorData"]))
        raw_ad[32] = raw_ad[32] ^ 0x04  # Flip an unused flag bit
        payload["response"]["authenticatorData"] = b64url_encode(bytes(raw_ad))

        with pytest.raises(ValueError, match="Invalid WebAuthn assertion signature"):
            verify_authentication_response(payload, chal, "localhost", "http://testserver")


# ==============================================================================
# 2. CBOR Attestation Parsing & Public Key Extraction
# ==============================================================================

@pytest.mark.django_db
class TestCBORAttestationParsing:
    """Challenge CBOR parsing against authentic browser formats and hostile inputs."""

    def test_browser_attestation_format_none_and_subsequent_assertion(self, crypto_user_setup):
        """Browser CBOR map with fmt='none' unpacks authData and correctly registers uncompressed EC point."""
        user = crypto_user_setup["user"]
        priv_key = crypto_user_setup["private_key"]
        pub_point = crypto_user_setup["public_point"]

        x_bytes = pub_point[0].to_bytes(32, "big")
        y_bytes = pub_point[1].to_bytes(32, "big")
        cose_key = {1: 2, 3: -7, -1: 1, -2: x_bytes, -3: y_bytes}
        cose_bytes = cbor_encode(cose_key)

        rp_hash = hashlib.sha256(b"localhost").digest()
        cred_id = b64url_encode(secrets.token_bytes(24))
        cred_id_bytes = b64url_decode(cred_id)
        auth_data = (
            rp_hash
            + bytes([0x41])  # UP | AT
            + struct.pack(">I", 0)
            + bytes(16)
            + struct.pack(">H", len(cred_id_bytes))
            + cred_id_bytes
            + cose_bytes
        )

        att_obj = {"fmt": "none", "attStmt": {}, "authData": auth_data}
        chal = b64url_encode(secrets.token_bytes(32))
        client_data = {"type": "webauthn.create", "challenge": chal, "origin": "http://testserver"}

        reg_payload = {
            "id": cred_id,
            "rawId": cred_id,
            "type": "public-key",
            "response": {
                "clientDataJSON": b64url_encode(json.dumps(client_data).encode("utf-8")),
                "attestationObject": b64url_encode(cbor_encode(att_obj)),
            },
        }

        res = verify_registration_response(reg_payload, chal, "localhost", user, "http://testserver")
        assert res["credential_id"] == cred_id
        extracted_point = b64url_decode(res["public_key"])
        assert len(extracted_point) == 65
        assert extracted_point[0] == 0x04
        assert extracted_point[1:33] == x_bytes
        assert extracted_point[33:65] == y_bytes

        # Save credential and verify assertion works with extracted key
        new_cred = PasskeyCredential.objects.create(
            user=user,
            credential_id=cred_id,
            public_key=res["public_key"],
            sign_count=0,
        )
        auth_chal = b64url_encode(secrets.token_bytes(32))
        assertion = build_mock_assertion_payload(
            credential_id=new_cred.credential_id,
            challenge=auth_chal,
            sign_count=1,
            private_key=priv_key,
        )
        auth_res = verify_authentication_response(assertion, auth_chal, "localhost", "http://testserver")
        assert auth_res["user"] == user
        new_cred.refresh_from_db()
        assert new_cred.sign_count == 1

    def test_browser_attestation_format_packed(self, crypto_user_setup):
        """Browser CBOR map with fmt='packed' unpacks authData and matches public key."""
        user = crypto_user_setup["user"]
        pub_point = crypto_user_setup["public_point"]

        x_bytes = pub_point[0].to_bytes(32, "big")
        y_bytes = pub_point[1].to_bytes(32, "big")
        cose_key = {1: 2, 3: -7, -1: 1, -2: x_bytes, -3: y_bytes}
        cose_bytes = cbor_encode(cose_key)

        rp_hash = hashlib.sha256(b"localhost").digest()
        cred_id = "packed-browser-cred-id"
        cred_id_bytes = cred_id.encode("utf-8")
        auth_data = (
            rp_hash
            + bytes([0x41])
            + struct.pack(">I", 0)
            + bytes(16)
            + struct.pack(">H", len(cred_id_bytes))
            + cred_id_bytes
            + cose_bytes
        )

        att_obj = {"fmt": "packed", "attStmt": {"alg": -7, "sig": b"mock_sig"}, "authData": auth_data}
        chal = b64url_encode(secrets.token_bytes(32))
        client_data = {"type": "webauthn.create", "challenge": chal, "origin": "http://testserver"}

        reg_payload = {
            "id": cred_id,
            "type": "public-key",
            "response": {
                "clientDataJSON": b64url_encode(json.dumps(client_data).encode("utf-8")),
                "attestationObject": b64url_encode(cbor_encode(att_obj)),
            },
        }

        res = verify_registration_response(reg_payload, chal, "localhost", user, "http://testserver")
        extracted_point = b64url_decode(res["public_key"])
        assert len(extracted_point) == 65
        assert extracted_point[0] == 0x04

    def test_cbor_attestation_rp_id_hash_mismatch_rejected(self, crypto_user_setup):
        """Attestation with RP ID hash bound to phishing domain is rejected."""
        user = crypto_user_setup["user"]
        evil_rp_hash = hashlib.sha256(b"attacker-domain.com").digest()
        auth_data = evil_rp_hash + bytes([0x41]) + struct.pack(">I", 0) + bytes(16) + struct.pack(">H", 5) + b"12345"

        att_obj = {"fmt": "none", "attStmt": {}, "authData": auth_data}
        chal = b64url_encode(secrets.token_bytes(32))
        client_data = {"type": "webauthn.create", "challenge": chal, "origin": "http://testserver"}

        reg_payload = {
            "id": "evil-rp-cred",
            "type": "public-key",
            "response": {
                "clientDataJSON": b64url_encode(json.dumps(client_data).encode("utf-8")),
                "attestationObject": b64url_encode(cbor_encode(att_obj)),
            },
        }

        with pytest.raises(ValueError, match="RP ID hash mismatch"):
            verify_registration_response(reg_payload, chal, "localhost", user, "http://testserver")

    def test_cbor_malformed_byte_streams_gracefully_rejected(self, crypto_user_setup):
        """Malformed or truncated CBOR attestationObject does not crash the server."""
        user = crypto_user_setup["user"]
        chal = b64url_encode(secrets.token_bytes(32))

        corrupt_streams = [
            b"",
            b"\xa3\x63fmt",
            b"\x58\xff\x01\x02",
            b"\x1f",
            b"\xff\xff\xff",
        ]
        for bad_bytes in corrupt_streams:
            reg_payload = {
                "id": "bad-cbor-cred",
                "type": "public-key",
                "response": {
                    "clientDataJSON": b64url_encode(json.dumps({"type": "webauthn.create", "challenge": chal, "origin": "http://testserver"}).encode()),
                    "attestationObject": b64url_encode(bad_bytes),
                },
            }
            with pytest.raises(ValueError):
                verify_registration_response(reg_payload, chal, "localhost", user, "http://testserver")


# ==============================================================================
# 3. ECDSA Pure-Python Mathematical Invariants
# ==============================================================================

class TestECDSAMathematicalInvariants:
    """Stress test pure-Python P-256 arithmetic against boundary conditions and invalid points."""

    def test_ecdsa_r_zero_or_s_zero_rejected(self):
        """Signatures with r=0 or s=0 evaluate to False."""
        pub_key = _scalar_mul(12345, P256_G)
        assert pub_key is not None
        msg = b"message to verify"

        sig_r0 = b"\x30\x06\x02\x01\x00\x02\x01\x01"
        assert verify_ecdsa_p256_signature(pub_key, msg, sig_r0) is False

        sig_s0 = b"\x30\x06\x02\x01\x01\x02\x01\x00"
        assert verify_ecdsa_p256_signature(pub_key, msg, sig_s0) is False

    def test_ecdsa_r_or_s_greater_than_order_rejected(self):
        """Signatures with r >= N or s >= N evaluate to False."""
        pub_key = _scalar_mul(12345, P256_G)
        assert pub_key is not None
        msg = b"message to verify"

        sig_rN = der_encode_signature(P256_N, 1)
        assert verify_ecdsa_p256_signature(pub_key, msg, sig_rN) is False

        sig_sN = der_encode_signature(1, P256_N)
        assert verify_ecdsa_p256_signature(pub_key, msg, sig_sN) is False

    def test_ecdsa_point_off_curve_and_infinity_rejected(self):
        """Points not satisfying y^2 = x^3 - 3x + b (mod p) or (0,0) evaluate to False."""
        msg = b"message to verify"
        dummy_sig = der_encode_signature(1, 1)

        # Off-curve point
        assert verify_ecdsa_p256_signature((123, 456), msg, dummy_sig) is False
        # Point at infinity
        assert verify_ecdsa_p256_signature((0, 0), msg, dummy_sig) is False


# ==============================================================================
# 4. Anti-Rollback Counter Hardening
# ==============================================================================

@pytest.mark.django_db
class TestAntiRollbackCounterHardening:
    """Verify monotonic counter enforcement and clone detection."""

    def test_sign_count_regression_raises_403_and_preserves_db(self, crypto_user_setup):
        """Counter regression (sign_count < stored) returns strict HTTP 403 and leaves DB untouched."""
        cred = crypto_user_setup["credential"]
        cred.sign_count = 10
        cred.save()

        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        payload = build_mock_assertion_payload(
            credential_id=cred.credential_id,
            challenge=server_chal,
            sign_count=9,  # Regression
            private_key=crypto_user_setup["private_key"],
        )

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 403
        assert "rollback detected" in resp.json().get("error", "").lower()

        cred.refresh_from_db()
        assert cred.sign_count == 10

    def test_sign_count_duplicate_raises_403_and_preserves_db(self, crypto_user_setup):
        """Duplicate counter (sign_count == stored) returns strict HTTP 403."""
        cred = crypto_user_setup["credential"]
        cred.sign_count = 10
        cred.save()

        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        payload = build_mock_assertion_payload(
            credential_id=cred.credential_id,
            challenge=server_chal,
            sign_count=10,  # Duplicate
            private_key=crypto_user_setup["private_key"],
        )

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 403
        assert "rollback detected" in resp.json().get("error", "").lower()

        cred.refresh_from_db()
        assert cred.sign_count == 10

    def test_sign_count_monotonic_increment_succeeds(self, crypto_user_setup):
        """Monotonic counter increment (sign_count > stored) succeeds and updates database."""
        cred = crypto_user_setup["credential"]
        cred.sign_count = 10
        cred.save()

        client = Client()
        opt_resp = client.post(reverse("auth:webauthn_login_options"), data=json.dumps({}), content_type="application/json")
        server_chal = opt_resp.json()["challenge"]

        payload = build_mock_assertion_payload(
            credential_id=cred.credential_id,
            challenge=server_chal,
            sign_count=11,  # Increment
            private_key=crypto_user_setup["private_key"],
        )

        resp = client.post(
            reverse("auth:webauthn_login_verify"),
            data=json.dumps({"credential": payload}),
            content_type="application/json",
        )
        assert resp.status_code == 200
        assert resp.json()["success"] is True

        cred.refresh_from_db()
        assert cred.sign_count == 11
