# Generated by Django 5.2.3 on 2025-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image_url_alter_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original recipe URL', unique=True),
        ),
    ]
