# Generated by Django 5.2.3 on 2025-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
