# Generated by Django 5.2.3 on 2026-02-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipetag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_future',
            field=models.BooleanField(default=False, help_text='Is this a recipe I want to try in the future?'),
        ),
    ]
