# Generated by Django 5.2.3 on 2026-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='ready_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
