# Generated by Django 5.2.3 on 2026-02-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_mealplan_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
