# Generated by Django 5.2.3 on 2026-03-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_mealplan_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_on_menu',
            field=models.BooleanField(default=False, help_text='Is this recipe currently on my weekly menu?'),
        ),
    ]
