# Generated by Django 5.2.3 on 2026-04-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_is_on_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original recipe URL', null=True, unique=True),
        ),
    ]
