# Generated by Django 5.2.3 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_future',
            field=models.BooleanField(default=False, help_text='Save to try in the future'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_on_menu',
            field=models.BooleanField(default=False, help_text='Add to weekly menu'),
        ),
    ]
