# Generated by Django 5.2.3 on 2026-09-23 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_enforce_scoping_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe_original_url_per_household',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(condition=models.Q(('original_url__isnull', False), models.Q(('original_url', ''), _negated=True)), fields=('household', 'original_url'), name='unique_recipe_original_url_per_household'),
        ),
    ]
