# Generated by Django 5.2.3 on 2026-09-23 02:25

from django.db import migrations, models


def make_existing_recipes_shared(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Recipe.objects.filter(is_shared=False).update(is_shared=True)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_remove_recipe_unique_recipe_original_url_per_household_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Share this recipe across households'),
        ),
        migrations.RunPython(make_existing_recipes_shared, migrations.RunPython.noop),
    ]

