"""
Django settings for KitchenClip project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from celery.schedules import crontab
from pathlib import Path
import os
import json
import warnings

# This package is required by recipe-scrapers but not ready for python3.13 ignore the log lines, nothings broken
warnings.filterwarnings(
    "ignore",
    category=SyntaxWarning,
    module="pyRdfa.*"
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / '.env'
if env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-fallback-key-for-local-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")
CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "https://127.0.0.1").split(",")
USE_X_FORWARDED_HOST = os.environ.get("USE_X_FORWARDED_HOST", "0") == "1"
USE_X_FORWARDED_PORT = os.environ.get("USE_X_FORWARDED_PORT", "0") == "1"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recipes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KitchenClip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KitchenClip.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
        'OPTIONS': {
            # Wait up to 20s for a write lock before raising OperationalError
            # This prevents 'database is locked' errors with multiple Gunicorn workers
            'timeout': 20,
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Chicago'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
if os.environ.get("CLOUDFLARE_ENABLED", "0") == "1":
    auth_index = MIDDLEWARE.index(
        "django.contrib.auth.middleware.AuthenticationMiddleware"
    )
    MIDDLEWARE.insert(
        auth_index + 1,
        "KitchenClip.middleware.cloudflare.CloudflareLoginMiddleware",
    )
    AUTHENTICATION_BACKENDS = [
        "recipes.backends.cloudflare.CloudflareAccessBackend"
    ]

ACCESS_ROLE_MAP = json.loads(os.environ.get('ACCESS_ROLE_MAP', '{}'))
TRUSTED_LOCAL_SUBNETS = json.loads(os.environ.get('TRUSTED_LOCAL_SUBNETS', '[]'))
LOCAL_ADMIN_EMAIL = os.environ.get('LOCAL_ADMIN_EMAIL', '')

# Cooking Notifications
DEFAULT_LUNCH_TIME = "12:00"
DEFAULT_DINNER_TIME = "18:30"
BEACON_URL = os.environ.get("BEACON_URL", "https://beacon.soehlert.com/homeassistant/alert")
ENABLE_COOKING_NOTIFICATIONS = os.environ.get("ENABLE_COOKING_NOTIFICATIONS", "0") == "1"

# Celery Configuration
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/1")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'check-upcoming-meals-every-15-mins': {
        'task': 'recipes.tasks.check_upcoming_meals_task',
        'schedule': crontab(minute='*/15'),
    },
}

TAG_COLORS = [
    "#1abc9c",  # teal
    "#2ecc71",  # green
    "#3498db",  # blue
    "#9b59b6",  # purple
    "#34495e",  # dark blue-gray
    "#16a085",  # dark teal
    "#27ae60",  # dark green
    "#2980b9",  # dark blue
    "#8e44ad",  # dark purple
    "#2c3e50",  # navy
    "#f39c12",  # orange
    "#d35400",  # dark orange
    "#e67e22",  # carrot
    "#e74c3c",  # red
    "#c0392b",  # dark red
    "#7f8c8d",  # gray
    "#95a5a6",  # light gray
    "#bdc3c7",  # silver
    "#f1c40f",  # yellow
    "#7ed6df",  # light blue
    "#e17055",  # coral
    "#fdcb6e",  # sand
    "#636e72",  # graphite
    "#00b894",  # greenish teal
    "#00cec9",  # cyan
    "#6c5ce7",  # soft purple
    "#a29bfe",  # lavender
    "#fd79a8",  # pink
    "#e84393",  # magenta
    "#00b8d4",  # dark cyan
    "#0097a7",  # teal blue
    "#00695c",  # dark green-teal
    "#4a148c",  # deep purple
    "#1a237e",  # indigo
    "#0d47a1",  # royal blue
    "#01579b",  # steel blue
    "#006064",  # dark cyan-green
    "#bf360c",  # rust
    "#3e2723",  # brown
    "#795548",  # medium brown
]
