"""
Django settings for KitchenClip project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings

# This package is required by recipe-scrapers but not ready for python3.13 ignore the log lines, nothings broken
warnings.filterwarnings(
    "ignore",
    category=SyntaxWarning,
    module="pyRdfa.*"
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_file = BASE_DIR / '.env'
if env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recipes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KitchenClip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KitchenClip.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAG_COLORS = [
    "#1abc9c",  # teal
    "#2ecc71",  # green
    "#3498db",  # blue
    "#9b59b6",  # purple
    "#34495e",  # dark blue-gray
    "#16a085",  # dark teal
    "#27ae60",  # dark green
    "#2980b9",  # dark blue
    "#8e44ad",  # dark purple
    "#2c3e50",  # navy
    "#f39c12",  # orange
    "#d35400",  # dark orange
    "#e67e22",  # carrot
    "#e74c3c",  # red
    "#c0392b",  # dark red
    "#7f8c8d",  # gray
    "#95a5a6",  # light gray
    "#bdc3c7",  # silver
    "#f1c40f",  # yellow
    "#7ed6df",  # light blue
    "#e17055",  # coral
    "#fdcb6e",  # sand
    "#636e72",  # graphite
    "#00b894",  # greenish teal
    "#00cec9",  # cyan
    "#6c5ce7",  # soft purple
    "#a29bfe",  # lavender
    "#fd79a8",  # pink
    "#e84393",  # magenta
    "#00b8d4",  # dark cyan
    "#0097a7",  # teal blue
    "#00695c",  # dark green-teal
    "#4a148c",  # deep purple
    "#1a237e",  # indigo
    "#0d47a1",  # royal blue
    "#01579b",  # steel blue
    "#006064",  # dark cyan-green
    "#bf360c",  # rust
    "#3e2723",  # brown
    "#795548",  # medium brown
]
